#!/bin/bash

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
    # geometry="$(($2-2))x$3"
    chafa -f sixel -s "$2x$3" --animate off --polite on "$1" | fold -w 65535
}

batorcat() {
	file="$1"
	shift
	if command -v bat > /dev/null 2>&1
	then
		bat --color=always --style=plain --pager=never "$file" "$@"
	else
		cat "$file"
	fi
}

glowormdcat() {
	file="$1"
	shift
	if command -v glow > /dev/null 2>&1
	then
		glow "$file"
	else
		mdcat "$file"
	fi
}

getcache_dir() {
    if [[ $1 == /home/*/secret/* ]]; then
        echo "/temp/.cache-lf-thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    else
        echo "${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    fi
}

case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
	*.tgz|*.tar.gz) tar tzf "$1" ;;
	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
	*.tar.txz|*.txz) xz --list "$1" ;;
	*.tar) tar tf "$1" ;;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
	*.rar) unrar l "$1" ;;
    *.md) glowormdcat "$1";;
	*.7z) 7z l "$1" ;;
	*.[1-8]) man "$1" | col -b ;;
	*.o) nm "$1";;
	*.torrent) transmission-show "$1" ;;
	*.iso) iso-info --no-header -l "$1" ;;
	*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
	*.doc) catdoc "$1" ;;
	*.docx) docx2txt "$1" ;;
    *.xml|*.html) w3m -dump "$1";;
	*.xls|*.xlsx)
		ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batorcat --language=csv
		;;
	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
		exiftool "$1"
		;;
	*.pdf)
        CACHE="$(getcache_dir "$1")"
		[ ! -f "${CACHE}.jpg" ] && \
			pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
        CACHE="$(getcache_dir "$1")"
		[ ! -f "${CACHE}.jpg" ] && ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.tiff|*.gif|*.jfif|*.ico)
		image "$1" "$2" "$3" "$4" "$5"
		;;
    *.svg)
        CACHE="$(getcache_dir "$1")"
        [ ! -f "${CACHE}.jpg" ] && convert "$1" "${CACHE}.jpg"
        image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
        ;;
	*.ino)
		batorcat --language=cpp "$1"
		;;
	*) case "$(file --dereference --brief --mime-type -- "$1")" in
        image/*) image "$1" "$2" "$3" "$4" "$5" ;;
        text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
        text/troff) man ./ "$1" | col -b ;;
        text/* | */xml | application/json) bat --terminal-width "$4" -f "$1" ;;
        application/zip) atool --list -- "$1" ;;
        audio/* | application/octet-stream) mediainfo "$1" || exit 1;;
        video/* )
            CACHE="$(getcache_dir "$1")"
            [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
            image "$CACHE" "$2" "$3" "$4" "$5"
            ;;
        */pdf)
            CACHE="$(getcache_dir "$1")"
            [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
            image "$CACHE.jpg" "$2" "$3" "$4" "$5"
            ;;
        *opendocument*) odt2txt "$1" ;;
        application/pgp-encrypted) gpg -d -- "$1" ;;
        *) batorcat "$1" ;;
    esac
esac
exit 0
