#!/usr/bin/sh
export QT_QPA_PLATFORMTHEME="qt5ct"
export PAGER="bat"
export EDITOR="nvim"

export MANWIDTH=999
export MANPAGER='nvim +Man!'
# export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
# export MSRCDIR="$HOME/.src"
# export MLCFGDIR="$MSRCDIR/dotfiles"
# export NPM_CONFIG_PREFIX="$HOME/.local"
export PATH="$PATH:$NPM_CONFIG_PREFIX/bin"
export GOPATH="$HOME/.local/share/go"
export PATH="$PATH:$HOME/.cargo/bin"
# export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:$HOME/go/bin"
# export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.local/bin"
export LANG="en_US.UTF-8"
# export GPG_TTY="$(tty)"
