#!/usr/bin/sh
export GDK_BACKEND=wayland
export TERMINAL="footclient"
export MOZ_ENABLE_WAYLAND=1
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM="wayland;xcb"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export _JAVA_AWT_WM_NONEREPARENTING=1
export CLUTTER_BACKEND="wayland"
