#!/usr/bin/sh
export TERMINAL="st"
#if !SYSTEMD
# xautolock -time 15 -locker "slock & loginctl suspend" -detectsleep &
# else
# xautolock -time 15 -locker "slock & systemctl suspend" -detectsleep &
#endif
# xautolock -time 10 -locker slock -detectsleep -notify 30 -notifier "notify-send -u critical -t 10000 'Screen Lock' 'Locking screen after 30s.'" &
# setxkbmap -layout us,ir -option grp:alt_shift_toggle &
# xmodmap ~/.config/xmodmap/xmodmaprc &
# feh --bg-scale "/usr/share/backgrounds/wallpapers/wallpaper_7.jpg" &
# picom --experimental-backends &
# xset r rate 300 30
