$zenWs = workspace 12
$mblWs = workspace 13
$vmWs = workspace 15
$telWs = workspace 16
$obsWs = workspace 18
$qbtWs = workspace 19

exec-once = waybar -c ~/.config/waybar/config-pc.jsonc
exec-once = blueman-applet

cursor {
    default_monitor = DP-1
}

monitorv2 {
  output = DP-1
  mode = preferred
  position = 0x0
  scale = 1
}

monitorv2 {
  output = HDMI-A-1
  mode = preferred
  position = 1920x0
  scale = 1
}

workspace = 1, persistent:true, monitor:DP-1, layout:master, default:true
workspace = 2, persistent:true, monitor:DP-1, layout:monocle
workspace = 3, persistent:true, monitor:DP-1
workspace = 4, persistent:true, monitor:DP-1, layout:monocle
workspace = 5, persistent:true, monitor:DP-1
workspace = 6, persistent:true, monitor:DP-1
workspace = 7, persistent:true, monitor:DP-1
workspace = 8, persistent:true, monitor:DP-1
workspace = 9, persistent:true, monitor:DP-1
workspace = 10, persistent:true, monitor:DP-1

workspace = 11, persistent:true, monitor:HDMI-A-1, layout:master, default:true
workspace = 12, persistent:true, monitor:HDMI-A-1, layout:monocle
workspace = 13, persistent:true, monitor:HDMI-A-1
workspace = 14, persistent:true, monitor:HDMI-A-1, layout:monocle
workspace = 15, persistent:true, monitor:HDMI-A-1
workspace = 16, persistent:true, monitor:HDMI-A-1
workspace = 17, persistent:true, monitor:HDMI-A-1
workspace = 18, persistent:true, monitor:HDMI-A-1
workspace = 19, persistent:true, monitor:HDMI-A-1
workspace = 20, persistent:true, monitor:HDMI-A-1
