$mblWs = workspace 15
$vmWs = workspace 17
$zenWs = workspace 18
$obsWs = workspace 20
$qbtWs = workspace 21

exec-once = sleep 1 && gentoo-pipewire-launcher
exec-once = /usr/libexec/hyprpolkitagent
exec-once = sleep 1 && waybar -c ~/.config/waybar/config-pc.jsonc
