preload = ~/.src/wallpapers/wallpaper_07.jpg
preload = ~/.src/wallpapers/wallpaper_26.png
preload = ~/.src/wallpapers/wallpaper_27.png

wallpaper = ,~/.src/wallpapers/wallpaper_27.png
wallpaper = DP-1,~/.src/wallpapers/wallpaper_27.png
wallpaper = HDMI-A-1,~/.src/wallpapers/wallpaper_27.png

splash = false
ipc = false
