general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 570
    on-timeout = dunstify -r 10000 -u critical -t 30000 -a 'hypridle' 'locking the system in 30s'
    on-resume = dunstify -C 10000
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
