$zenWs = workspace 14
$mblWs = workspace 15
$vmWs = workspace 17
$telWs = workspace 18
$obsWs = workspace 20
$qbtWs = workspace 21

exec-once = waybar -c ~/.config/waybar/config-pc.jsonc

cursor {
    default_monitor = Virtual-1
}

monitorv2 {
  output = Virtual-1
  mode = 1920x1080@60.00
  position = 1920x0
  scale = 1
}

workspace = 1, persistent:true, monitor:Virtual-1, layout:master, default:true
workspace = 2, persistent:true, monitor:Virtual-1, layout:monocle
workspace = 3, persistent:true, monitor:Virtual-1, layout:scrolling
workspace = 4, persistent:true, monitor:Virtual-1, layout:monocle
workspace = 5, persistent:true, monitor:Virtual-1, layout:scrolling
workspace = 6, persistent:true, monitor:Virtual-1, layout:scrolling
workspace = 7, persistent:true, monitor:Virtual-1, layout:scrolling
workspace = 8, persistent:true, monitor:Virtual-1, layout:scrolling
workspace = 9, persistent:true, monitor:Virtual-1, layout:scrolling
workspace = 10, persistent:true, monitor:Virtual-1, layout:master
