$zenWs = workspace 14
$mblWs = workspace 15
$vmWs = workspace 17
$telWs = workspace 18
$obsWs = workspace 20
$qbtWs = workspace 21

exec-once = waybar -c ~/.config/waybar/config-pc.jsonc

monitorv2 {
  output = Virtaul-1
  mode = 1920x1080@60
  position = 1920x0
  scale = 1
}
