$zenWs = workspace 2
$mblWs = workspace 3
$vmWs = workspace 5
$telWs = workspace 6
$obsWs = workspace 8
$qbtWs = workspace 9

exec-once = waybar -c ~/.config/waybar/config-laptop.jsonc
exec-once = blueman-applet

cursor {
    default_monitor = eDP-1
}

monitorv2 {
  output = eDP-1
  mode = preferred
  position = 0x0
  scale = 1
}

workspace = 1, persistent:true, monitor:eDP-1, layout:master, default:true
workspace = 2, persistent:true, monitor:eDP-1, layout:monocle
workspace = 3, persistent:true, monitor:eDP-1
workspace = 4, persistent:true, monitor:eDP-1, layout:monocle
workspace = 5, persistent:true, monitor:eDP-1
workspace = 6, persistent:true, monitor:eDP-1
workspace = 7, persistent:true, monitor:eDP-1
workspace = 8, persistent:true, monitor:eDP-1
workspace = 9, persistent:true, monitor:eDP-1
workspace = 10, persistent:true, monitor:eDP-1
