[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_symlink = false

[preview]
cache_dir = "~/.cache/yazi/thumbnails"

[plugin]
prepend_fetchers = [
    { id = "mime", if = "!(mime|dummy)", name = "*", run = "mime-ext", prio = "high" },
    { id = "git", name = "*", run = "git" },
    { id = "git", name = "*/", run = "git" },
]

prepend_previewers = [
    { name = "/.files/share", run = "noop" },
    { mime = "application/{*zip,x-tar,x-bzip2,x-7z-compressed,x-rar,x-xz}", name = "*.{tar.gz,tar.xz}", run = "ouch" },
    { name = "*.md",                        run = "glow" },
    # { mime = "text/csv",                    run = "miller"},
    { mime = "audio/*",                     run = "exifaudio"},
]

prepend_preloaders = [
    { name = "/.files/share", run = "noop" },
]

[opener]
play = [
    { run = "mpv %s", orphan = true, for = "unix" },
]

pdff = [
    { run = 'zathura "$@"', desc = "zathura", orphan = true, block = false, for = "unix" },
]

add-sub = [
    { run  = '''echo sub-add "'$0'" | socat - /tmp/mpv.sock''', desc = "Add sub to MPV" },
]

ouch-decompress = [
    { run  = '''ouch decompress -y "$@"''', desc = "decompress" },
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = [ "pdff", "reveal" ] },
    { name = "*.{ass,srt,ssa,sty,sup,vtt}", use = [ "add-sub", "edit" ]},
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
    { mime = "application/{*zip,x-tar,x-bzip2,x-7z-compressed,x-rar,x-xz}", name = "*.{tar.gz,tar.xz}", use = [ "ouch-decompress", "reveal" ] },
]
