[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_symlink = false

[preview]
cache_dir = "~/.cache/yazi/thumbnails"

[plugin]
prepend_fetchers = [
    # { group = "mime", id = "mime", if = "!(mime|dummy)", url = "*", run = "mime-ext", prio = "high" },
    { group = "git", id = "git", url = "*", run = "git" },
    { group = "git", id = "git", url = "*/", run = "git" },
]

prepend_previewers = [
    { url = "/.files/share", run = "noop" },
    { mime = "application/{*zip,x-tar,x-bzip2,x-7z-compressed,x-rar,x-xz}", url = "*.{tar.gz,tar.xz}", run = "ouch" },
    { url = "*.md",                        run = "glow" },
    # { mime = "text/csv",                    run = "miller"},
    { mime = "audio/*",                     run = "exifaudio"},
]

prepend_preloaders = [
    { url = "/.files/share", run = "noop" },
]

[opener]
play = [
    { run = "mpv %s", orphan = true, for = "unix" },
]

pdff = [
    { run = 'zathura %s', desc = "zathura", orphan = true, block = false, for = "unix" },
]

add-sub = [
    { run  = '''echo sub-add "'$0'" | socat - /tmp/mpv.sock''', desc = "Add sub to MPV" },
]

ouch-decompress = [
    { run  = '''ouch decompress -y "$@"''', desc = "decompress" },
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = [ "pdff", "reveal" ] },
    { mime = "application/epub+zip", use = [ "pdff", "reveal" ] },
    { url  = "*.{ass,srt,ssa,sty,sup,vtt}", use = [ "add-sub", "edit" ]},
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
    { mime = "application/{*zip,x-tar,x-bzip2,x-7z-compressed,x-rar,x-xz}", url = "*.{tar.gz,tar.xz}", use = [ "ouch-decompress", "reveal" ] },
]
