regexp=(\d+)% packet loss
colours=red
=======
regexp=([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*?:.*?bytes.*?time=
colours=green
=======
regexp=(\d+)\s+errors
colours=red
=======
regexp=Unreachable
colours=red
=======
regexp=timed out
colours=red
=======
regexp=(\d+\.\d+ ms)
colours=green
